# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8mlmEQOu88VHvS99uoa-ul8lj9nwD0b
"""

!pip install -U scikit-learn==1.5.2 imbalanced-learn==0.12.3 shap tensorflow
!nvidia-smi

import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
import numpy as np
import os

# Optional: allow GPU memory growth (avoids OOM errors)
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("GPU is ready")
    except RuntimeError as e:
        print(e)

from google.colab import drive
drive.mount('/content/drive')

# Create a project folder in Drive
project_path = "/content/drive/MyDrive/HeartDisease_CVDD"
import os
os.makedirs(project_path, exist_ok=True)
print("Project folder:", project_path)

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['heart_2020_cleaned.csv']))

import random, time
import numpy as np
import pandas as pd
from math import sqrt
from scipy.stats import pointbiserialr

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from imblearn.over_sampling import ADASYN

import tensorflow as tf
from tensorflow.keras import layers, Model, Input
from tensorflow.keras.optimizers import Adam

import shap

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

print("Setup done.")

# 🔍 Auto-detect target column (first column containing 'heart')
target_col = None
for col in df.columns:
    if "heart" in col.lower():
        target_col = col
        break

if target_col is None:
    raise ValueError("❌ Could not find target column automatically. Please check dataset columns!")

print("✅ Target column detected:", target_col)

# Target mapping
if df[target_col].dtype == object:
    df[target_col] = df[target_col].map({"No": 0, "Yes": 1})

X = df.drop(columns=[target_col])
y = df[target_col].astype(int)

# Balance with ADASYN
adasyn = ADASYN(random_state=SEED)
X_res, y_res = adasyn.fit_resample(X, y)

# PBCC feature selection
pbcc_scores = {col: abs(pointbiserialr(X_res[col], y_res)[0]) for col in X_res.columns}
pbcc_df = pd.Series(pbcc_scores).sort_values(ascending=False)

PBCC_THRESHOLD = 0.02
selected_features = pbcc_df[pbcc_df >= PBCC_THRESHOLD].index.tolist()
if len(selected_features) == 0:
    selected_features = pbcc_df.index[:10].tolist()

X_sel = X_res[selected_features].copy()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_sel)

n_features = X_scaled.shape[1]
print("Final features:", n_features)

def build_lenet_1d(input_shape):
    inp = Input(shape=(input_shape, 1))
    x = layers.Conv1D(32, 5, activation="tanh", padding="same")(inp)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Conv1D(8, 5, activation="tanh", padding="same")(x)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Conv1D(16, 1, activation="tanh", padding="same")(x)
    x = layers.Flatten()(x)
    x = layers.Dense(32, activation="tanh")(x)
    x = layers.Dense(16, activation="tanh")(x)
    x = layers.Dense(4, activation="tanh")(x)
    out = layers.Dense(1, activation="sigmoid")(x)
    return Model(inp, out, name="LeNet1D")

def build_gru_small(input_shape):
    inp = Input(shape=(input_shape, 1))
    x = layers.GRU(17, return_sequences=True)(inp)
    x = layers.GRU(17)(x)
    out = layers.Dense(1, activation="sigmoid")(x)
    return Model(inp, out, name="GRU_small")

def build_mlp_meta():
    inp = Input(shape=(2,))
    x = layers.Dense(16, activation="relu")(inp)
    x = layers.Dense(8, activation="relu")(x)
    out = layers.Dense(1, activation="sigmoid")(x)
    return Model(inp, out, name="MLP_meta")

def build_enscvdd_net(input_shape):
    lenet = build_lenet_1d(input_shape)
    gru = build_gru_small(input_shape)
    inp = Input(shape=(input_shape,1))
    out1, out2 = lenet(inp), gru(inp)
    concat = layers.concatenate([out1, out2])
    final = layers.Dense(1, activation="sigmoid")(concat)
    return Model(inp, final, name="EnsCVDD-Net")

import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
import numpy as np
import os

# ---------------- GPU Setup ----------------
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("GPU is ready")
    except RuntimeError as e:
        print(e)

# ---------------- Hyperparameters ----------------
EPOCHS = 20
BATCH_SIZE = 64
LR = 0.001

# ---------------- Data ----------------
X_all = X_scaled.astype(np.float32)  # Ensure float32
y_all = y_res.astype(np.float32)

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=SEED)

ens_acc, bl_acc = [], []

for fold, (train_idx, test_idx) in enumerate(skf.split(X_all, y_all), 1):
    print(f"\nFold {fold}")

    # Train/Test Split
    X_train, X_test = X_all[train_idx], X_all[test_idx]
    y_train, y_test = y_all[train_idx], y_all[test_idx]

    # Reshape for 1D CNN/GRU input
    X_train_r = X_train.reshape(-1, n_features, 1)
    X_test_r = X_test.reshape(-1, n_features, 1)

    # ---------------- Create tf.data.Dataset ----------------
    train_ds = tf.data.Dataset.from_tensor_slices((X_train_r, y_train))
    train_ds = train_ds.shuffle(buffer_size=len(X_train_r))
    train_ds = train_ds.batch(BATCH_SIZE)
    train_ds = train_ds.prefetch(tf.data.AUTOTUNE)

    test_ds = tf.data.Dataset.from_tensor_slices((X_test_r, y_test))
    test_ds = test_ds.batch(BATCH_SIZE)
    test_ds = test_ds.prefetch(tf.data.AUTOTUNE)

    # ---------------- EnsCVDD ----------------
    model_ens = build_enscvdd_net(n_features)
    model_ens.compile(optimizer=Adam(LR), loss="binary_crossentropy", metrics=["accuracy"])
    model_ens.fit(train_ds, epochs=EPOCHS, verbose=1)

    preds_ens = (model_ens.predict(test_ds, verbose=0).ravel() >= 0.5).astype(int)
    acc = accuracy_score(y_test, preds_ens)
    ens_acc.append(acc)
    print("EnsCVDD Accuracy:", acc)

    # Save EnsCVDD model
    model_path = f"{project_path}/enscvdd_fold{fold}.h5"
    model_ens.save(model_path)
    print("Saved:", model_path)

    # ---------------- BlCVDD ----------------
    lenet = build_lenet_1d(n_features)
    gru = build_gru_small(n_features)
    lenet.compile(optimizer=Adam(LR), loss="binary_crossentropy")
    gru.compile(optimizer=Adam(LR), loss="binary_crossentropy")

    lenet.fit(train_ds, epochs=EPOCHS, verbose=1)
    gru.fit(train_ds, epochs=EPOCHS, verbose=1)

    # Meta features for MLP
    p1 = lenet.predict(test_ds, verbose=0).ravel()
    p2 = gru.predict(test_ds, verbose=0).ravel()
    meta_features = np.vstack([p1, p2]).T

    mlp = build_mlp_meta()
    mlp.compile(optimizer=Adam(LR), loss="binary_crossentropy")
    mlp.fit(meta_features, y_test, epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=1)

    preds_bl = (mlp.predict(meta_features, verbose=0).ravel() >= 0.5).astype(int)
    acc_b = accuracy_score(y_test, preds_bl)
    bl_acc.append(acc_b)
    print("BlCVDD Accuracy:", acc_b)

    # Save BlCVDD meta-learner
    mlp.save(f"{project_path}/blcvdd_meta_fold{fold}.h5")